name: my-main-workflow

on:
  schedule:
    - cron: '*/7 * * * *'
  workflow_dispatch:
  
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use My Workflow
        uses: ./.github/workflows/schedule.yml
