name: On Push Workflow

on:
  push:
    branches: ["test-push"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print message
        run: echo "Workflow triggered on push to a branch other than main."
