name: Test reusable
on:
  workflow_call:
    secrets:
      test:
        required: true
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: | 
         echo ${{secrets.test}}
