name: Scheduled Workflow
on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch:
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout code
      #  uses: actions/checkout@v2
      - name: Display Current Time
        run: |
            echo "The current time is $(date)."
            ls -ltr
      - name: Use My Action
        uses: ./.github/actions/test
