name: Scheduled Workflow
on:
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display Current Time
        run: echo "The current time is $(date)."
