name: Scheduled Workflow
on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch:
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display Current Time
        run: echo "The current time is $(date)."
