name: start
on: [push]


jobs:
  run-github-actions:
    runs-on: ubuntu-18.04
    steps:
      - name: Simple Js
        run : echo "Hello Js"
      - name: Calling other action
        id: JSAction
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Rachit
        
      - name: Using jsaction output
        run: echo "${{steps.JSAction.outputs.time}}"

  run-with-docker:
    runs-on: ubuntu-18.04
    container:
      image: node:10.18.0-jessie
    steps:
      - name: log node version
        run: node -v
      - uses: actions/checkout@v1
      - name: change permission
      - run: >
          cat /etc/os-release
          ls -ltr
          
          chmod +x ./hello.sh


      - name: Step with docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "./hello.sh"
          args: "-a"  


