name: start
on: [push]


jobs:
  run-github-actions:
    runs-on: ubuntu-18.04
    steps:
      - name: Simple Js
        run : echo "Hello Js"
      - name: Calling other action
        id: JSAction
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Rachit
        
      - name: Using jsaction output
        run: echo ${{steps.JSAction.outputs.time}}
