name: Reusable Workflow

on:
  workflow_call:
    inputs:
      test:
        default: 'YES'
        type: string

jobs:
  conditional-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check input value
        if: contains(github.event.inputs.test, 'YES')
        run: |
          if [ "${{ github.event.inputs.test }}" == "YES" ]; then
            echo "Input value is YES"
            # Add the steps you want to run when the input value is YES
          else
            echo "Input value is not YES"
            # Add any fallback steps or skip execution altogether
          fi
