name: Reusable Workflow

on:
  workflow_call:
    inputs:
      test:
        default: true
        type: boolean

jobs:
  conditional-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check input value
        if: github.events.inputs.test
        run: |
          if [ ${{ github.event.inputs.test }}" ]; then
            echo "Input value is YES"
            # Add the steps you want to run when the input value is YES
          else
            echo "Input value is not YES"
            # Add any fallback steps or skip execution altogether
          fi
