name: Trigger Reusable Workflow

on:
  push:
    branches-ignore: 
      - master

jobs:
  trigger-job:
    uses: RachitGupta008/github-actions/.github/workflows/test_call.yaml@master
    with:
      test: true
