name: Trigger Reusable Workflow

on:
  push:
    branches-ignore: 
      - master

jobs:
  trigger-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Reusable Workflow
        uses: ./.github/workflows/reusable-workflow.yml
        with:
          test: "YES"
